### ISSUE TITLE
Arcanist bug "You are running an old version of cslint. Please upgrade to version 1."

### ISSUE THREAD

**Issue by lavahot** [hach-que/cstools#4]
I'm stumped on this one. I compiled cslint in visual studio, did a dry run `cslint.exe -v` and everything seems to work. I get a `1` followed by an empty line. I thought maybe the parser wasn't working correctly, so I recompiled it with `Console.Write("1")` instead of `Console.WriteLine("1"). This makes it not emit the newline, but I get the same error. I'm up to date on arcanist, and I followed the instructions to install on Windows to the letter. Thoughts?

**Comment by hach-que** [comment]
I'm in the process of completely replacing cslint with a new tool that provides better auto patching called csast. 

If you want to try it out, add this repo as a Git submodule and checkout the ast branch. Then add the submodule as a library to load in .arcconfig like so: 

```
{
  "load": ["cstools"]
}
```

Then update your .arclint to have something like this: 

```
{
  "linters": {
    "merge-conflict": {
      "type": "merge-conflict"
    },
    "csharp-ast": {
      "type": "csharp-ast",
      "include": "(^.+\\.cs$)"
    }
  }
}
```

This new linter does not require configuration of discovery maps or project files. 

Let me know if this new linter works for you.
