### ISSUE TITLE
cslint compile fails

### ISSUE THREAD

**Issue by nunohorta** [hach-que/cstools#6]
I was trying to compile cslint but it's throwing the following error:

`Implementations/StyleCopLinter.cs(56,53): error CS1061: Type `StyleCop.CodeProject' does not contain a definition for `ViolationsAsErrors' and no extension method `ViolationsAsErrors' of type `StyleCop.CodeProject' could be found. Are you missing an assembly reference?`

I've reverted the changes of this [commit](https://github.com/hach-que/cstools/commit/5b3a7c985210ad50972e97eaf52c3697df03929b) and it's seems to work

**Comment by hach-que** [comment]
This project is no longer maintained.  Visual Studio Analyzers pretty much supersede the functionality of this project in every way, so I recommend using those instead.
